//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Effect()
        {
            this.BodyHealthEffect = new HashSet<BodyHealthEffect>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] MainIcon { get; set; }
        public int HealingMethodId { get; set; }
        public int HeadHpDecrease { get; set; }
        public int TorsoHpDecrease { get; set; }
        public int StomachHpDecrease { get; set; }
        public int LeftHandHpDecrease { get; set; }
        public int RightHandHpDecrease { get; set; }
        public int LeftLegHpDecrease { get; set; }
        public int RightLegHpDecrease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyHealthEffect> BodyHealthEffect { get; set; }
        public virtual HealingMethod HealingMethod { get; set; }
    }
}
