//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyHealth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BodyHealth()
        {
            this.BodyHealthEffect = new HashSet<BodyHealthEffect>();
        }
    
        public int Id { get; set; }
        public int HeadHp { get; set; }
        public int TorsoHp { get; set; }
        public int StomachHp { get; set; }
        public int LeftHandHp { get; set; }
        public int RightHandHp { get; set; }
        public int LeftLegHp { get; set; }
        public int RightLegHp { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodyHealthEffect> BodyHealthEffect { get; set; }
    }
}
