//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyHealthEffect
    {
        public int Id { get; set; }
        public int BodyHealthId { get; set; }
        public int EffectId { get; set; }
    
        public virtual BodyHealth BodyHealth { get; set; }
        public virtual Effect Effect { get; set; }
    }
}
