//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyHealth
    {
        public int Id { get; set; }
        public float HeartSystemReaction { get; set; }
        public float IndexOfMass { get; set; }
        public int BreathHoldingDuration { get; set; }
        public int Score { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateOfFill { get; set; }
    
        public virtual User User { get; set; }
    }
}
