//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormForDoctors
    {
        public int Id { get; set; }
        public System.DateTime DateOfFill { get; set; }
        public bool Neurologist { get; set; }
        public bool Rheumatologist { get; set; }
        public bool Otolaryngologist { get; set; }
        public bool Gastroenterologist { get; set; }
        public bool Allergist { get; set; }
        public bool FullInspection { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
