//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalScore
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MinScore { get; set; }
        public int MaxScore { get; set; }
        public int MedicalTestId { get; set; }
    
        public virtual MedicalTest MedicalTest { get; set; }
    }
}
