//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCard
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int UserId { get; set; }
        public float Height { get; set; }
        public float Weight { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
