//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealHealthBaseEntities : DbContext
    {
        public RealHealthBaseEntities()
            : base("name=RealHealthBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyHealth> BodyHealth { get; set; }
        public virtual DbSet<BodyHealthEffect> BodyHealthEffect { get; set; }
        public virtual DbSet<CodeQuestion> CodeQuestion { get; set; }
        public virtual DbSet<Effect> Effect { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HealingMethod> HealingMethod { get; set; }
        public virtual DbSet<MedicalAnswer> MedicalAnswer { get; set; }
        public virtual DbSet<MedicalCard> MedicalCard { get; set; }
        public virtual DbSet<MedicalQuestion> MedicalQuestion { get; set; }
        public virtual DbSet<MedicalScore> MedicalScore { get; set; }
        public virtual DbSet<MedicalTest> MedicalTest { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserMedicalTest> UserMedicalTest { get; set; }
    }
}
