//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMedicalTest
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MedicalTestId { get; set; }
        public System.DateTime CompleteDate { get; set; }
    
        public virtual MedicalTest MedicalTest { get; set; }
        public virtual User User { get; set; }
    }
}
